config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :recipes, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :genres, only: [:index, :new, :create ,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]

  resources :recipes do
    resources :comments
    post :confirm, on: :collection
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # コメントを保存、投稿するためのアクションです。
  def create
    # recipeをパラメータの値から探し出し,recipeに紐づくcommentsとしてbuild
    @comment = current_user.comments.build(comment_params)
    @recipe = @comment.recipe
    @comment = current_user.comments.build(comment_params)
    @recipe = @comment.recipe
    @notification = @comment.notifications.build(user_id: @recipe.user.id )
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @comment.save
        format.html { redirect_to recipe_path(@recipe), notice: 'コメントを投稿しました。' }
        format.js { render :index }

        unless @comment.recipe.user_id == current_user.id
          Pusher.trigger("user_#{@comment.recipe.user_id}_channel", 'comment_created', {
            message: 'あなたの作成したレシピにコメントが付きました'
          })
        end
        Pusher.trigger("user_#{@comment.recipe.user_id}_channel", 'notification_created', {
          unread_counts: Notification.where(user_id: @comment.recipe.user.id, read: false).count
        })

      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to recipe_path(@recipe), notice: 'コメントを削除しました。' }
      format.html { render :index }
      format.js { render :index }
    end
  end

  private
    # ストロングパラメーター
    def comment_params
      params.require(:comment).permit(:recipe_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([recipe,comment], remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= comment.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :recipe_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容"  %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <li>
        <p class="left"><%= comment.user.name %>さんがコメントしました。</p>
        <p class="left"><%= comment.content %></p>
        <% if current_user.id == comment.user.id %>
          <p class="right">
            <%= link_to '', edit_recipe_comment_path(recipe, comment), class: "fa fa-pencil-square-o fa-lg" %>
            <%= link_to '', recipe_comment_path(recipe, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
          </p>
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.recipe.comments, recipe: @comment.recipe }) %>")
$(':text').val('')