config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :recipes, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :genres, only: [:index, :new, :create ,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]

  resources :recipes do
    resources :comments
    post :confirm, on: :collection
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  #titleへの空の値の入力を禁止
  validates :title,  presence: true
  mount_uploader :recipe_image, RecipeImageUploader
  mount_uploader :process_image_01, RecipeImageUploader
  mount_uploader :process_image_02, RecipeImageUploader
  mount_uploader :process_image_03, RecipeImageUploader
  mount_uploader :process_image_04, RecipeImageUploader
  mount_uploader :process_image_05, RecipeImageUploader
  mount_uploader :process_image_06, RecipeImageUploader
  mount_uploader :process_image_07, RecipeImageUploader
  mount_uploader :process_image_08, RecipeImageUploader
  mount_uploader :process_image_09, RecipeImageUploader
  mount_uploader :process_image_10, RecipeImageUploader
  mount_uploader :process_image_11, RecipeImageUploader
  mount_uploader :process_image_12, RecipeImageUploader
  belongs_to :user
  # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  #ログインしていないと機能使用不可
  before_action :authenticate_user!
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    #入力フォームと一覧を表示するためインスタンスを2つ生成
    @comment = @recipe.comments.build
    @comments = @recipe.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end

  # GET /recipes/new
  def new
    if params[:back]
      @recipe = Recipe.new(recipes_params)
    else
      @recipe = Recipe.new
    end
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipes_params)
    #user.idも合わせて登録
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
        #send_mailのメソッドを呼び出す
        NoticeMailer.sendmail_recipe(@recipe).deliver
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipes_params)
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @recipe = Recipe.new(recipes_params)
    render :new if @recipe.invalid?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipes_params
      params.require(:recipe).permit(:title, :knack, :comment, :genre, :recipe_image, :recipe_image_cache, :remove_recipe_image, :material_01, :material_02, :material_03, :material_04, :material_05, :material_06, :material_07, :material_08, :material_09, :material_10, :material_11, :material_12, :material_13, :material_14, :material_15, :material_16, :material_17, :material_18, :material_19, :material_20, :process_image_01, :process_image_01_cache, :remove_process_image_01, :process_image_02, :process_image_02_cache, :remove_process_image_02, :process_image_03, :process_image_03_cache, :remove_process_image_03, :process_image_04, :process_image_04_cache, :remove_process_image_04, :process_image_05, :process_image_05_cache, :remove_process_image_05, :process_image_06, :process_image_06_cache, :remove_process_image_06, :process_image_07, :process_image_07_cache, :remove_process_image_07, :process_image_08, :process_image_08_cache, :remove_process_image_08, :process_image_09, :process_image_09_cache, :remove_process_image_09, :process_image_10, :process_image_10_cache, :remove_process_image_10, :process_image_11, :process_image_11_cache, :remove_process_image_11, :process_image_12, :process_image_12_cache, :remove_process_image_12, :process_01, :process_02, :process_03, :process_04, :process_05, :process_06, :process_07, :process_08, :process_09, :process_10, :process_11, :process_12 )
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_recipes_path
    elsif action_name == 'edit'
      recipe_path
    end
  end
end

app/views/recipes/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= form_for(@recipe) do |f| %>
      <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
      <%= f.hidden_field :title %>
      <%= f.hidden_field :knack %>
      <%= f.hidden_field :recipe_image %>
      <!-- @recipe.titleと@recipe.contentとすることで、表示用の値を画面に出力しています。 -->
      <p>タイトル:<%= @recipe.title %></p>
      <p>本文:<%= @recipe.knack %></p>
      <!-- 投稿画像 追加箇所 開始 -->
      <p>
        <% if recipe.recipe_image? %>
          <div class="thumbnail">
            <%= image_tag recipe.recipe_image %>
          </div>
        <% end %>
      </p>
      <!-- 投稿画像 追加箇所 終了 -->
      <%= f.submit "登録する" %>
    <% end %>
    <%= form_for(@recipe, url: new_recipe_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :knack %>
      <%= f.hidden_field :recipe_image %>
      <%= f.submit "もどる", name: 'back' %>
    <% end %>
</div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<div class="container">
  <div class="col-md-12">
    <%= render 'form' %>
    <%= link_to 'Show', @recipe %> |
    <%= link_to 'Back', recipes_path %>
  </div>
</div>

app/views/recipes/index.html.erb
<p id="notice">
<%= notice %>
</p>

<div class="container_index">
  <ul>
  <% @recipes.each do |recipe| %>
    <div class="elements">
      <%= link_to recipe_path(recipe) do %>
        <li>
          <div class="frame_01">
            <img src="<%= recipe.recipe_image %>" onError=this.src="<%= asset_path "no_image.png" %>">
          </div>
          <%= recipe.title %>
        </li>
      <% end %>
    </div>
  <% end %>
  </ul>
</div>
<div class="clear"><hr /></div>

app/views/recipes/new.html.erb
<h1>NEW DIYレシピ</h1>

<div class="container">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="show_p">
  <%= notice %>
</div>


<div class="wrapper clearfix">
  <div class="left_menu">
    <!--タイトル-->
    <div class="text-01">
        <%= @recipe.title %>
    </div>
    <!--レシピ画像-->
    <p class="recipe_image">
        <img src="<%= @recipe.recipe_image %>" onError=this.src="<%= asset_path "no_image.png" %>">

    </p>
  </div>


  <div class="right_menu">
        <!--プロファイル画像-->
        <div class="img-pro">
        <%= profile_img(@recipe.user) %><!--ユーザ画像-->
        <% if current_user.id == @recipe.user_id %>
　        <%= link_to "編集", edit_recipe_path(@recipe), class: 'square_btn btn-default btn-sm' %>
          <%= link_to "削除", recipe_path(@recipe.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'square_btn btn-default btn-sm' %>
        <% end %>
　        <%= link_to "一覧", recipes_path, class: 'square_btn btn-default btn-sm' %>
  　    </div>
        <!--ジャンル-->
        <div class="text-genre">
         ジャンル：<%= @recipe.genre %>
        </div>
        <!--コメント-->
        <div class="text-comment">
          <%= @recipe.comment %>
        </div>
        <!--材料-->
        <div class="text-material">
          <p><%= @recipe.material_01 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_02 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_03 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_04 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_05 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_06 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_07 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_08 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_09 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_10 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_11 %><br>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_12 %><br>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_13 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_14 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_15 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_16 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_17 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_18 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_19 %></p>
          <hr width=80% color="#7d7d7d" style="border-style:dotted">
          <p><%= @recipe.material_20 %></p>
        </div>
  </div>

</div>



<div id="container">
  <ul>
    <!--手順01-->
    <div class="elements_process">
      <li><div class="process_number">
        手順.01
      </div></li>
      <li><div class="frame_process">
          <img src="<%= asset_path @recipe.process_image_01 %>" onError=this.src="<%= asset_path "no_image.png" %>">
      </div></li>
      <li><div class="frame_process_text">
        <%= @recipe.process_01 %>
      </div></li>
   </div>

   <!--手順02-->
   <div class="elements_process">
     <li><div class="process_number">
       手順.02
     </div></li>
     <li><div class="frame_process">
         <img src="<%= asset_path @recipe.process_image_02 %>" onError=this.src="<%= asset_path "no_image.png" %>">
     </div></li>
     <li><div class="frame_process_text">
       <%= @recipe.process_02 %>
     </div></li>
  </div>

  <!--手順03-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.03
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_03 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_03 %>
    </div></li>
 </div>

 <!--手順04-->
 <div class="elements_process">
   <li><div class="process_number">
     手順.04
   </div></li>
   <li><div class="frame_process">
       <img src="<%= asset_path @recipe.process_image_04 %>" onError=this.src="<%= asset_path "no_image.png" %>">
   </div></li>
   <li><div class="frame_process_text">
     <%= @recipe.process_04 %>
   </div></li>
  </div>

  <!--手順05-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.05
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_05 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_05 %>
    </div></li>
  </div>

  <!--手順06-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.06
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_06 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_06 %>
    </div></li>
  </div>

  <!--手順07-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.07
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_07 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_07 %>
    </div></li>
  </div>

  <!--手順08-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.08
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_08 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_08 %>
    </div></li>
  </div>

  <!--手順09-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.09
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_09 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_09 %>
    </div></li>
  </div>

  <!--手順010-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.10
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_10 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_10 %>
    </div></li>
  </div>

  <!--手順11-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.11
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_11 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_11 %>
    </div></li>
  </div>

  <!--手順12-->
  <div class="elements_process">
    <li><div class="process_number">
      手順.12
    </div></li>
    <li><div class="frame_process">
        <img src="<%= asset_path @recipe.process_image_12 %>" onError=this.src="<%= asset_path "no_image.png" %>">
    </div></li>
    <li><div class="frame_process_text">
      <%= @recipe.process_12 %>
    </div></li>
  </div>
  </ul>
</div>

   <div class="knac">
     <div class="left_menu_knac">
      <img src="<%= asset_path "point.png" %>">
    </div>
    <div class="right_menu_knac">
      <p><%= @recipe.knack %></p>
    </div>
  </div>

<div class="child row">
  <div class="wrapper_comment col-md-12">
    <h1><p>コメント一覧</p></h1>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, recipe: @recipe } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, recipe: @recipe } %>

  </div>
</div>