config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :recipes, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :genres, only: [:index, :new, :create ,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]

  resources :recipes do
    resources :comments
    post :confirm, on: :collection
  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    #emailへの空の値の入力を禁止
    validates :email,  presence: true
    #contentへの空の値の入力を禁止
    validates :content,  presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contacts_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contact was successfully created.' }
        NoticeMailer.sendmail_contact(@contact).deliver
        NoticeMailer.sendmail_contactadmin(@contact).deliver        
      else
        format.html { render :new }
      end
    end
  end

  def confirm
    @contact = Contact.new(contacts_params)
    render :new if @contact.invalid?
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :email, :content)
    end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, url: confirm_contacts_path) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <br>

    <%= f.submit %>

<% end %>

app/views/contacts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<div class="container">
  <div class="col-md-12">
    <%= form_for(@contact) do |f| %>
      <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :content %>
      <!-- 表示用の値を画面に出力しています。 -->
      <p>Name:<%= @contact.name %></p>
      <p>E-Mail:<%= @contact.email %></p>
      <p>本文:<%= @contact.content %></p>
      <%= f.submit "登録する" %>
    <% end %>
    <%= form_for(@contact, url: new_contact_path, method: 'get') do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back' %>
    <% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <%= form_for(@contact, url:confirm_contacts_path) do |f| %>
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>
      <br>
      <%= f.label :"E-mail" %>
      <%= f.text_field :email, class: 'form-control' %>
      <br>
      <%= f.label :内容 %>
      <%= f.text_field :content, class: 'form-control' %>
      <br>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

<!--
<h1>問い合わせ</h1>

<div class="container">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>
<%= link_to 'Back', root_path %>
-->