config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  resources :recipes, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :genres, only: [:index, :new, :create ,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only: [:index, :show]

  resources :recipes do
    resources :comments
    post :confirm, on: :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
  <!-- meta data & title -->
  <title>Hachiroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--アラートポップアップ用-->
  <% if user_signed_in? %>
  <script>
    var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
      encrypted: true,
      cluster: 'ap1'
    });

    var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
    channel.bind('comment_created', function(data) {
      alert(data.message);
    });
    channel.bind('notification_created', function(data) {
      $('#unread_count').html(data.unread_counts);
    });
  </script>
  <% end %>

</head>
<body>

  <!-- Header -->
  <header>
    <%= link_to root_path do %>
    <img src="<%= asset_path "HachiRoom-logo.png" %>" class="logo_image">
    <% end %>
    <ul>
      <li><%= link_to 'DIYレシピ', recipes_path  %></li>
      <li><%= link_to '問い合わせ', new_contact_path  %></li>
      <% if user_signed_in? %>
　　      <li><%= link_to notifications_index_path, class: "navbar-brand" do %>
  　　      <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
  　　    <% end %></li>
        <li><%= link_to 'New Recipe', new_recipe_path if user_signed_in? %></li>
        <li><%= link_to 'ユーザー一覧', users_path if user_signed_in? %></li>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
    </ul>
  </header>
  <!-- End Header -->

<%= yield %>

<footer>
  <p>運営会社 hachi room</p>
  <p>© 2017 Copyright IMAMURA.Lab</p>
</footer>

</body>
</html>